### ISSUE TITLE
the classname of the explanation card

### ISSUE THREAD

**Issue by ghost** [troop129/QuizletAnswers#1]
The classname of the explanation card seems to be changed from `hs7m9cv s1oluvjw`
to `ExplanationSolutionsContainer hnqbbas s1oluvjw`.

By the way, I recommend the tag `overflow:visible` instead of `overflow:scroll`.
Then the whole content is visible with no need to scroll or delete `max-height`.

**Comment by josephyooo** [comment]
these changes seem to fix it..
#2

**Comment by troop129** [comment]
Merged, will add some more logic to complete changes
